name = "myapp-worker"
main = "src/worker.js"
type = "javascript"
account_id = "8fe4c98145f75ec4b181a54270f116b8"
compatibility_date = "2026-08-01"

# Optional: set environment variables here for static values. Secrets MUST be set via
# `wrangler secret put HF_API_KEY` or in the Cloudflare dashboard (recommended).
# To use different environments, add an [env.production] table, etc.

[build]
command = ""

[vars]
# HF_API_KEY = "" # don't commit secrets here
